### ISSUE TITLE
Create Public API route for get by token id

### ISSUE THREAD

**Issue by fadnesscharlie** [follow-the-nft/follow-the-nft-api#23]
Add a GET request route to the API to fetch a [single asset](https://docs.opensea.io/reference/retrieving-a-single-asset).

**Comment by fadnesscharlie** [comment]
Account Model:
Address
User
Config


Grab from API:
Token Id
Name
Image_url
description?
external_link
owner
traits
last_sale

**Comment by MuckT** [comment]
Closed by #25.
