### ISSUE TITLE
Create the `requirements.md`

### ISSUE THREAD

**Issue by MuckT** [follow-the-nft/follow-the-nft-api#5]
Take notes from the our group meeting and create the `requirements.md` based on [Code Fellows Software Requirements Doc](https://codefellows.github.io/common_curriculum/projects/SoftwareReqs).

**Comment by fadnesscharlie** [comment]
Branch as been made under "softwareRequirement" for Template in markdown

**Comment by fadnesscharlie** [comment]
Create the diagram schema, as you have a better idea of what data is going to be in there

**Comment by vbchomp** [comment]
I think we have the rest of the software requirements.md doc done and projPrep #4 done. It just needs the schema.
